### ISSUE TITLE
Route vote

### ISSUE THREAD

**Issue by RobWar-code** [RobWar-code/sample-project#1]
In order to **choose a route** as a **participant**, I can **vote for a preferred route**

# Acceptance Criteria
1. Routes appear on a list
2. Routes can be ticked for the poll
3. Routes can be amended by an administrator

# Tasks                                                                                              Story Points
- [x] Create a database table of routes                                                      1
- [ ] Create an on screen list of routes with radio buttons                          3
- [ ] Create a route list editor for administrators                                         8

**Comment by RobWar-code** [comment]
This item is completed.
