### ISSUE TITLE
Poll Event Response

### ISSUE THREAD

**Issue by RobWar-code** [RobWar-code/sample-project#5]
In order to **provide my opinion to a certain running topic or event** as a **user**, I can **select and submit a response from the poll**

Total SP 4

##Acceptance Criteria
There should be a response button adjacent to the poll
When the response button is clicked, a pop-up appears for entering response text

##Tasks
- [ ] Front-End Button, SP 1
- [ ] Response Text-Area Operation SP 3
- [ ] Backend Record of User and Response SP 1
