### ISSUE TITLE
User Story: Poll Response Comments

### ISSUE THREAD

**Issue by RobWar-code** [RobWar-code/sample-project#7]
In order to **provide comments before submitting the poll response** as a **user**, I can **add an additional comment**

Total SP 2

## Acceptance Criteria
A drop-down box for a comment appears when the comment button is clicked

## Tasks
- [ ] Comment button on poll response form SP 0.5
- [ ] Drop down comment box SP 0.5
- [ ] Update tables SP 1
